### ISSUE TITLE
Mac OSX version

### ISSUE THREAD

**Issue by domtancredi** [dagguh/netrunner#69]
Would it be possible to output a release for Mac? I'd love to download and playtest

**Comment by dagguh** [comment]
Sure thing! [v0.0.2](https://github.com/dagguh/netrunner/releases/tag/v0.0.2) included a [Mac version](https://github.com/dagguh/netrunner/releases/download/v0.0.2/Netrunner-0.0.2-mac.zip). I'll make sure to include it for v0.0.3 too 🙂 
Relates to #33

**Comment by dagguh** [comment]
Let me know if it works for you

**Comment by dagguh** [comment]
I added some [playtesting guidance](https://github.com/dagguh/netrunner/blob/f86156927940b6f6add1506807683f8431e9ffc6/Docs/PLAYTESTING.md), I hope it works 🤞

**Comment by domtancredi** [comment]
Looks good to me!
