### ISSUE TITLE
Emptying a server doesn't destroy the server

### ISSUE THREAD

**Issue by dagguh** [dagguh/netrunner#80]
In turn you can run an empty server and throw an exception

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by dagguh** [comment]
The initial fix uncovered a deeper problem. Overinstalling asset with an asset would destroy the server, because I'm reacting to cards-in-server count changes immediately. I'm refactoring the ad hoc installation code to match newly revised and simplified [NISEI rules](http://nisei.net/files/Comprehensive_Rules.pdf) - 8.3.

**Comment by dagguh** [comment]
Generic install match Comprehensive Rules much more closely now. Code actually got simpler, which is nice.
Still gotta handle the server destruction case though.

**Comment by dagguh** [comment]
Turns out, servers cease to exist due to rule 10.3.1.h
It's a part of checkpoints logic, so gotta add checkpoints!
