### ISSUE TITLE
Prepare some small documentation for playtesting

### ISSUE THREAD

**Issue by JeffSkyrunner** [dagguh/netrunner#82]
**Is your feature request related to a problem? Please describe.**
I have tried to play the 0.0.2 version, but really have no clue on what I am supposed to do :)

**Describe the solution you'd like**
I would like to have a brief checklist of the things I can try and what the release is about (i.e. "on this release you can only click on the run logo and see... something")

**Comment by dagguh** [comment]
Hey! Thanks for your interest in playtesting!
I updated the release descriptions in [0.0.1](https://github.com/dagguh/netrunner/releases/tag/v0.0.1) and [0.0.2](https://github.com/dagguh/netrunner/releases/tag/v0.0.2).

The [v0.0.3](https://github.com/dagguh/netrunner/projects/4) version has been brewing for some time, but it's almost done. You gave me the motivation to pick it up again 🙂

**Comment by JeffSkyrunner** [comment]
Excellent!

I wish I could be more proficient with Unity to help you more... at the
moment I have just forked the project and trying to document the code,
let's hope to learn something to help you also in coding :)
