### ISSUE TITLE
Rough roadmap/backlog

### ISSUE THREAD

**Issue by JeffSkyrunner** [dagguh/netrunner#83]
**Is your feature request related to a problem? Please describe.**
It is not very clear (to me) overview of what the project would like to implement in terms of game rules and automation and where the project is

**Describe the solution you'd like**
It would be nice to have a rough roadmap or an "epic backlog" to understand what is already implemented and what you think of implementing next :)

**Additional context**
Please consider this only a suggestion :)
It is just because I would like to understand where you are going to with the project, in order to help you better, if I could :)

**Comment by dagguh** [comment]
The overall vision is in the README right now: [design goals](https://github.com/dagguh/netrunner#design-goals).
You can look at [opened projects](https://github.com/dagguh/netrunner/projects?query=is%3Aopen) to see what's the current short-term plan.
You can look at [closed projects](https://github.com/dagguh/netrunner/projects?query=is%3Aclosed), to see what was already delivered.
You can look at [issues without projects](https://github.com/dagguh/netrunner/issues?q=no%3Aproject+is%3Aissue) as a long-term backlog. I browse through those when looking for tasks for a new version.

**Comment by dagguh** [comment]
@JeffSkyrunner feel free to add any new issues and even start a new project to define the next features to ship.

**Comment by JeffSkyrunner** [comment]
I will finish to have a general look at the full project, and then I will create epics/stories on my fork, if you agree: in that way, you can overview that and decide which are more compliant to your vision :)

**Comment by dagguh** [comment]
Awesome, I started watching your fork 🙂 
PS. shipped #80 today, only #61 is left for v0.0.3

**Comment by JeffSkyrunner** [comment]
I have shared a project containing Epics as I see them... please feel free to edit/change/discuss as you wish :)

Once this is set, I can create a project for each epic so that this could help you in keeping things ordered, if you like this way of proceeding :)

**Comment by dagguh** [comment]
Could you point me to the project?

**Comment by JeffSkyrunner** [comment]
Sorry, I thought an email would arrive you, since I set you as a collaborator :)

https://github.com/users/JeffSkyrunner/projects/1

**Comment by dagguh** [comment]
Ah, this project is not bound to your fork or any other repo. I'm gonna take a look.
The ideas are in the form of notes rather than issues, so I cannot comment on them. So I'll create new columns, like `Looks good` and `Requires reconsideration` and add my comments directly in the notes.

**Comment by JeffSkyrunner** [comment]
Yep, I haven't been able to link that to my repository after I have created
that, I don't know why.

Ok, once you have commented I can create proper "Epic" and "Story" projects
with linked issues, if you wish, so that it would be easier...

**Comment by JeffSkyrunner** [comment]
Created the proper project and issues.
I think we can close this now :)

**Comment by dagguh** [comment]
Let's close it when we get it nicely ported in this repo. I added you as a collaborator.
You could create new projects and populate them with issues.

In general, I want to arrive at a functioning game first. The cardpool can be low, the GUI can be ugly, but the core engine must work, so I focus on [gameplan](https://github.com/dagguh/netrunner/labels/gameplay) issues. I like to sprinkle a little of [look and feel](https://github.com/dagguh/netrunner/labels/look%20and%20feel) from time to time, to make the game more presentable and exciting.

**Comment by JeffSkyrunner** [comment]
I will move everything here then :)
Thanks for the opportunity.

I do agree on the plan and way to proceed, absolutely.

**Comment by dagguh** [comment]
Awesome, thanks for helping create the path forward.
If you want a more freeform/lightweight way to chat, we can use gitter: https://gitter.im/nisei-netrunner/unity-netrunner
Or we can try making a channel on Slack.

**Comment by JeffSkyrunner** [comment]
Done
