### ISSUE TITLE
Move "magic numbers" in a config file

### ISSUE THREAD

**Issue by JeffSkyrunner** [dagguh/netrunner#95]
To improve flexibility and future improvements, we should move "magic numbers" into an external/configuration file.

For example:

- numbers of starting credits
- numbers of click per turns
- numbers of initial cards to draw

**Comment by dagguh** [comment]
Do you have a concrete use case in mind?

**Comment by JeffSkyrunner** [comment]
For example, in the Corp class:

public void Start(Game game)
        {
            pilot.Play(game);
            credits.Gain(5); // TODO: this should be in an external config file
            zones.rd.Shuffle();
            zones.rd.Draw(5, zones.hq); // TODO: this should be in an external config file
        }

**Comment by NoahTheDuke** [comment]
What is the benefit here? I don't think Nisei will ever change these values.

**Comment by JeffSkyrunner** [comment]
Mainly two reasons:

1. the code would be cleaner;
2. in case we would like to introduce different way of playing (like the solo playing alternative rules or the multiplayer versions or some specific tutorials or many more situations...) it would be easier to have game rules in a specific game mode files, instead of hard coded;

**Comment by dagguh** [comment]
> the code would be cleaner

Subjective, IMHO it would be less readable.

> it would be easier to have game rules in a specific game mode files

For the user, it would be easier to have the game modes implemented in game. Also we can have a "custom game" mode to set up arbitrary starting conditions.
I also imagine a puzzle mode, where you have a given boardstate and you gotta win e.g. in 3 clicks. Complimentarily, we could have a boardstate editor, usable by custom games or for creating new puzzles. It would go way beyond a file with a few select numbers.

So I'm closing this one and raising the new ideas: #107, #108
